name: recipedia
description: Twoje ulubione przepisy w jednym miejscu
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  google_mlkit_text_recognition: ^0.13.1
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  file_picker: ^8.1.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
